version: "3.8"

services:
  pagina_solance:
    image: nginx:alpine
    container_name: pagina_solance
    ports:
      - "3007:3000"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - solance_network

networks:
  solance_network:
    driver: bridge
