version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: solance_residences_web
    ports:
      - "3020:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    networks:
      - solance_network

networks:
  solance_network:
    driver: bridge
